// Generated by gencpp from file dingo_msgs/Fans.msg
// DO NOT EDIT!


#ifndef DINGO_MSGS_MESSAGE_FANS_H
#define DINGO_MSGS_MESSAGE_FANS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dingo_msgs
{
template <class ContainerAllocator>
struct Fans_
{
  typedef Fans_<ContainerAllocator> Type;

  Fans_()
    : fan(0)  {
    }
  Fans_(const ContainerAllocator& _alloc)
    : fan(0)  {
  (void)_alloc;
    }



   typedef uint8_t _fan_type;
  _fan_type fan;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FAN_OFF)
  #undef FAN_OFF
#endif
#if defined(_WIN32) && defined(FAN_ON_HIGH)
  #undef FAN_ON_HIGH
#endif
#if defined(_WIN32) && defined(FAN_ON_LOW)
  #undef FAN_ON_LOW
#endif

  enum {
    FAN_OFF = 0u,
    FAN_ON_HIGH = 1u,
    FAN_ON_LOW = 2u,
  };


  typedef boost::shared_ptr< ::dingo_msgs::Fans_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dingo_msgs::Fans_<ContainerAllocator> const> ConstPtr;

}; // struct Fans_

typedef ::dingo_msgs::Fans_<std::allocator<void> > Fans;

typedef boost::shared_ptr< ::dingo_msgs::Fans > FansPtr;
typedef boost::shared_ptr< ::dingo_msgs::Fans const> FansConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dingo_msgs::Fans_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dingo_msgs::Fans_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dingo_msgs::Fans_<ContainerAllocator1> & lhs, const ::dingo_msgs::Fans_<ContainerAllocator2> & rhs)
{
  return lhs.fan == rhs.fan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dingo_msgs::Fans_<ContainerAllocator1> & lhs, const ::dingo_msgs::Fans_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dingo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dingo_msgs::Fans_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dingo_msgs::Fans_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dingo_msgs::Fans_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dingo_msgs::Fans_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dingo_msgs::Fans_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dingo_msgs::Fans_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dingo_msgs::Fans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01598dfa69c225015f34ed02ddca5d97";
  }

  static const char* value(const ::dingo_msgs::Fans_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01598dfa69c22501ULL;
  static const uint64_t static_value2 = 0x5f34ed02ddca5d97ULL;
};

template<class ContainerAllocator>
struct DataType< ::dingo_msgs::Fans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dingo_msgs/Fans";
  }

  static const char* value(const ::dingo_msgs::Fans_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dingo_msgs::Fans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Possible fan states\n"
"uint8 FAN_OFF=0\n"
"uint8 FAN_ON_HIGH=1\n"
"uint8 FAN_ON_LOW=2\n"
"\n"
"# Control for the fan\n"
"uint8 fan\n"
;
  }

  static const char* value(const ::dingo_msgs::Fans_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dingo_msgs::Fans_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fans_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dingo_msgs::Fans_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dingo_msgs::Fans_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "fan: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DINGO_MSGS_MESSAGE_FANS_H
