// Generated by gencpp from file dingo_msgs/Lights.msg
// DO NOT EDIT!


#ifndef DINGO_MSGS_MESSAGE_LIGHTS_H
#define DINGO_MSGS_MESSAGE_LIGHTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dingo_msgs/RGB.h>

namespace dingo_msgs
{
template <class ContainerAllocator>
struct Lights_
{
  typedef Lights_<ContainerAllocator> Type;

  Lights_()
    : lights()  {
    }
  Lights_(const ContainerAllocator& _alloc)
    : lights()  {
  (void)_alloc;
      lights.assign( ::dingo_msgs::RGB_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::dingo_msgs::RGB_<ContainerAllocator> , 4>  _lights_type;
  _lights_type lights;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LIGHTS_REAR_LEFT)
  #undef LIGHTS_REAR_LEFT
#endif
#if defined(_WIN32) && defined(LIGHTS_FRONT_LEFT)
  #undef LIGHTS_FRONT_LEFT
#endif
#if defined(_WIN32) && defined(LIGHTS_FRONT_RIGHT)
  #undef LIGHTS_FRONT_RIGHT
#endif
#if defined(_WIN32) && defined(LIGHTS_REAR_RIGHT)
  #undef LIGHTS_REAR_RIGHT
#endif

  enum {
    LIGHTS_REAR_LEFT = 0u,
    LIGHTS_FRONT_LEFT = 1u,
    LIGHTS_FRONT_RIGHT = 2u,
    LIGHTS_REAR_RIGHT = 3u,
  };


  typedef boost::shared_ptr< ::dingo_msgs::Lights_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dingo_msgs::Lights_<ContainerAllocator> const> ConstPtr;

}; // struct Lights_

typedef ::dingo_msgs::Lights_<std::allocator<void> > Lights;

typedef boost::shared_ptr< ::dingo_msgs::Lights > LightsPtr;
typedef boost::shared_ptr< ::dingo_msgs::Lights const> LightsConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dingo_msgs::Lights_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dingo_msgs::Lights_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dingo_msgs::Lights_<ContainerAllocator1> & lhs, const ::dingo_msgs::Lights_<ContainerAllocator2> & rhs)
{
  return lhs.lights == rhs.lights;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dingo_msgs::Lights_<ContainerAllocator1> & lhs, const ::dingo_msgs::Lights_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dingo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dingo_msgs::Lights_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dingo_msgs::Lights_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dingo_msgs::Lights_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dingo_msgs::Lights_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dingo_msgs::Lights_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dingo_msgs::Lights_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dingo_msgs::Lights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "548010051500e722f9ddd10ebf087f18";
  }

  static const char* value(const ::dingo_msgs::Lights_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x548010051500e722ULL;
  static const uint64_t static_value2 = 0xf9ddd10ebf087f18ULL;
};

template<class ContainerAllocator>
struct DataType< ::dingo_msgs::Lights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dingo_msgs/Lights";
  }

  static const char* value(const ::dingo_msgs::Lights_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dingo_msgs::Lights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents a command for the 4 RGB body lights on Dingo.\n"
"\n"
"uint8 LIGHTS_REAR_LEFT=0\n"
"uint8 LIGHTS_FRONT_LEFT=1\n"
"uint8 LIGHTS_FRONT_RIGHT=2\n"
"uint8 LIGHTS_REAR_RIGHT=3\n"
"\n"
"dingo_msgs/RGB[4] lights\n"
"\n"
"================================================================================\n"
"MSG: dingo_msgs/RGB\n"
"# Represents the intensity of a single RGB LED, either reported or commanded.\n"
"\n"
"uint8 red\n"
"uint8 green\n"
"uint8 blue\n"
;
  }

  static const char* value(const ::dingo_msgs::Lights_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dingo_msgs::Lights_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lights);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lights_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dingo_msgs::Lights_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dingo_msgs::Lights_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "lights: ";
    if (v.lights.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.lights.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::dingo_msgs::RGB_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.lights[i]);
    }
    if (v.lights.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DINGO_MSGS_MESSAGE_LIGHTS_H
