// Generated by gencpp from file dingo_msgs/RGB.msg
// DO NOT EDIT!


#ifndef DINGO_MSGS_MESSAGE_RGB_H
#define DINGO_MSGS_MESSAGE_RGB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dingo_msgs
{
template <class ContainerAllocator>
struct RGB_
{
  typedef RGB_<ContainerAllocator> Type;

  RGB_()
    : red(0)
    , green(0)
    , blue(0)  {
    }
  RGB_(const ContainerAllocator& _alloc)
    : red(0)
    , green(0)
    , blue(0)  {
  (void)_alloc;
    }



   typedef uint8_t _red_type;
  _red_type red;

   typedef uint8_t _green_type;
  _green_type green;

   typedef uint8_t _blue_type;
  _blue_type blue;





  typedef boost::shared_ptr< ::dingo_msgs::RGB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dingo_msgs::RGB_<ContainerAllocator> const> ConstPtr;

}; // struct RGB_

typedef ::dingo_msgs::RGB_<std::allocator<void> > RGB;

typedef boost::shared_ptr< ::dingo_msgs::RGB > RGBPtr;
typedef boost::shared_ptr< ::dingo_msgs::RGB const> RGBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dingo_msgs::RGB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dingo_msgs::RGB_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dingo_msgs::RGB_<ContainerAllocator1> & lhs, const ::dingo_msgs::RGB_<ContainerAllocator2> & rhs)
{
  return lhs.red == rhs.red &&
    lhs.green == rhs.green &&
    lhs.blue == rhs.blue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dingo_msgs::RGB_<ContainerAllocator1> & lhs, const ::dingo_msgs::RGB_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dingo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dingo_msgs::RGB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dingo_msgs::RGB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dingo_msgs::RGB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dingo_msgs::RGB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dingo_msgs::RGB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dingo_msgs::RGB_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dingo_msgs::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c2dad1f01296e5a2060415602019877";
  }

  static const char* value(const ::dingo_msgs::RGB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c2dad1f01296e5aULL;
  static const uint64_t static_value2 = 0x2060415602019877ULL;
};

template<class ContainerAllocator>
struct DataType< ::dingo_msgs::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dingo_msgs/RGB";
  }

  static const char* value(const ::dingo_msgs::RGB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dingo_msgs::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents the intensity of a single RGB LED, either reported or commanded.\n"
"\n"
"uint8 red\n"
"uint8 green\n"
"uint8 blue\n"
;
  }

  static const char* value(const ::dingo_msgs::RGB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dingo_msgs::RGB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red);
      stream.next(m.green);
      stream.next(m.blue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RGB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dingo_msgs::RGB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dingo_msgs::RGB_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "green: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.green);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "blue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DINGO_MSGS_MESSAGE_RGB_H
