// Generated by gencpp from file dingo_msgs/Status.msg
// DO NOT EDIT!


#ifndef DINGO_MSGS_MESSAGE_STATUS_H
#define DINGO_MSGS_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dingo_msgs
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , hardware_id(0)
    , firmware_version()
    , mcu_uptime()
    , connection_uptime()
    , pcb_temperature(0.0)
    , mcu_temperature(0.0)
    , stop_engaged(false)
    , drivers_active(false)
    , external_stop_present(false)
    , shore_power_connected(false)
    , shore_power_ov(false)
    , battery_connected(false)
    , power_12v_user_nominal(false)
    , manual_charger_connected(false)
    , measured_battery(0.0)
    , measured_12v(0.0)
    , measured_5v(0.0)
    , computer_current(0.0)
    , total_current(0.0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hardware_id(0)
    , firmware_version(_alloc)
    , mcu_uptime()
    , connection_uptime()
    , pcb_temperature(0.0)
    , mcu_temperature(0.0)
    , stop_engaged(false)
    , drivers_active(false)
    , external_stop_present(false)
    , shore_power_connected(false)
    , shore_power_ov(false)
    , battery_connected(false)
    , power_12v_user_nominal(false)
    , manual_charger_connected(false)
    , measured_battery(0.0)
    , measured_12v(0.0)
    , measured_5v(0.0)
    , computer_current(0.0)
    , total_current(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _hardware_id_type;
  _hardware_id_type hardware_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _firmware_version_type;
  _firmware_version_type firmware_version;

   typedef ros::Duration _mcu_uptime_type;
  _mcu_uptime_type mcu_uptime;

   typedef ros::Duration _connection_uptime_type;
  _connection_uptime_type connection_uptime;

   typedef float _pcb_temperature_type;
  _pcb_temperature_type pcb_temperature;

   typedef float _mcu_temperature_type;
  _mcu_temperature_type mcu_temperature;

   typedef uint8_t _stop_engaged_type;
  _stop_engaged_type stop_engaged;

   typedef uint8_t _drivers_active_type;
  _drivers_active_type drivers_active;

   typedef uint8_t _external_stop_present_type;
  _external_stop_present_type external_stop_present;

   typedef uint8_t _shore_power_connected_type;
  _shore_power_connected_type shore_power_connected;

   typedef uint8_t _shore_power_ov_type;
  _shore_power_ov_type shore_power_ov;

   typedef uint8_t _battery_connected_type;
  _battery_connected_type battery_connected;

   typedef uint8_t _power_12v_user_nominal_type;
  _power_12v_user_nominal_type power_12v_user_nominal;

   typedef uint8_t _manual_charger_connected_type;
  _manual_charger_connected_type manual_charger_connected;

   typedef float _measured_battery_type;
  _measured_battery_type measured_battery;

   typedef float _measured_12v_type;
  _measured_12v_type measured_12v;

   typedef float _measured_5v_type;
  _measured_5v_type measured_5v;

   typedef float _computer_current_type;
  _computer_current_type computer_current;

   typedef float _total_current_type;
  _total_current_type total_current;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(HARDWARE_ID_D100)
  #undef HARDWARE_ID_D100
#endif
#if defined(_WIN32) && defined(HARDWARE_ID_D150)
  #undef HARDWARE_ID_D150
#endif

  enum {
    HARDWARE_ID_D100 = 0u,
    HARDWARE_ID_D150 = 1u,
  };


  typedef boost::shared_ptr< ::dingo_msgs::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dingo_msgs::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::dingo_msgs::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::dingo_msgs::Status > StatusPtr;
typedef boost::shared_ptr< ::dingo_msgs::Status const> StatusConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dingo_msgs::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dingo_msgs::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dingo_msgs::Status_<ContainerAllocator1> & lhs, const ::dingo_msgs::Status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.hardware_id == rhs.hardware_id &&
    lhs.firmware_version == rhs.firmware_version &&
    lhs.mcu_uptime == rhs.mcu_uptime &&
    lhs.connection_uptime == rhs.connection_uptime &&
    lhs.pcb_temperature == rhs.pcb_temperature &&
    lhs.mcu_temperature == rhs.mcu_temperature &&
    lhs.stop_engaged == rhs.stop_engaged &&
    lhs.drivers_active == rhs.drivers_active &&
    lhs.external_stop_present == rhs.external_stop_present &&
    lhs.shore_power_connected == rhs.shore_power_connected &&
    lhs.shore_power_ov == rhs.shore_power_ov &&
    lhs.battery_connected == rhs.battery_connected &&
    lhs.power_12v_user_nominal == rhs.power_12v_user_nominal &&
    lhs.manual_charger_connected == rhs.manual_charger_connected &&
    lhs.measured_battery == rhs.measured_battery &&
    lhs.measured_12v == rhs.measured_12v &&
    lhs.measured_5v == rhs.measured_5v &&
    lhs.computer_current == rhs.computer_current &&
    lhs.total_current == rhs.total_current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dingo_msgs::Status_<ContainerAllocator1> & lhs, const ::dingo_msgs::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dingo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dingo_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dingo_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dingo_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dingo_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dingo_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dingo_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dingo_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "708b6ef299d359691b51cd4fc831d8e4";
  }

  static const char* value(const ::dingo_msgs::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x708b6ef299d35969ULL;
  static const uint64_t static_value2 = 0x1b51cd4fc831d8e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dingo_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dingo_msgs/Status";
  }

  static const char* value(const ::dingo_msgs::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dingo_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents Dingo's lower-frequency status updates\n"
"# Default publish frequency is 1Hz.\n"
"\n"
"Header header\n"
"\n"
"# Hardware ID\n"
"uint8 HARDWARE_ID_D100=0\n"
"uint8 HARDWARE_ID_D150=1\n"
"uint8 hardware_id\n"
"\n"
"# Commit of firmware source.\n"
"string firmware_version\n"
"\n"
"# Times since MCU power-on and MCU rosserial connection, respectively.\n"
"duration mcu_uptime\n"
"duration connection_uptime\n"
"\n"
"# Temperature of MCU's PCB in Celsius.\n"
"float32 pcb_temperature\n"
"float32 mcu_temperature\n"
"\n"
"# Monitoring the run/stop loop. Changes in these values trigger an immediate\n"
"# publish, outside the ordinarily-scheduled 1Hz updates.\n"
"#bool stop_power_status      # True indicates the stop loop is operational (ie. it is powered).\n"
"bool stop_engaged           # True when a stop has been pressed on the robot.\n"
"bool drivers_active         # False when a stop is asserted to the motor drivers.\n"
"bool external_stop_present  # True indicates a external stop has been plugged in.\n"
"\n"
"# Power connected readings\n"
"bool shore_power_connected    # Indicates if AC power is connected.\n"
"bool shore_power_ov           # Indicates if AC power is causing overvoltage.\n"
"bool battery_connected        # Indicates if battery is connected.\n"
"bool power_12v_user_nominal   # Indicates if the 12V user power is good.\n"
"bool manual_charger_connected # Indicates if manual charger is connected.\n"
"\n"
"# Voltage rails, in volts\n"
"# Averaged over the message period\n"
"float32 measured_battery\n"
"float32 measured_12v\n"
"float32 measured_5v\n"
"\n"
"# Current senses available on platform, in amps.\n"
"# Averaged over the message period\n"
"float32 computer_current\n"
"float32 total_current\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dingo_msgs::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dingo_msgs::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hardware_id);
      stream.next(m.firmware_version);
      stream.next(m.mcu_uptime);
      stream.next(m.connection_uptime);
      stream.next(m.pcb_temperature);
      stream.next(m.mcu_temperature);
      stream.next(m.stop_engaged);
      stream.next(m.drivers_active);
      stream.next(m.external_stop_present);
      stream.next(m.shore_power_connected);
      stream.next(m.shore_power_ov);
      stream.next(m.battery_connected);
      stream.next(m.power_12v_user_nominal);
      stream.next(m.manual_charger_connected);
      stream.next(m.measured_battery);
      stream.next(m.measured_12v);
      stream.next(m.measured_5v);
      stream.next(m.computer_current);
      stream.next(m.total_current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dingo_msgs::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dingo_msgs::Status_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hardware_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hardware_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "firmware_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.firmware_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mcu_uptime: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.mcu_uptime);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "connection_uptime: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.connection_uptime);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pcb_temperature: ";
    Printer<float>::stream(s, indent + "  ", v.pcb_temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mcu_temperature: ";
    Printer<float>::stream(s, indent + "  ", v.mcu_temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stop_engaged: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop_engaged);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "drivers_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.drivers_active);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "external_stop_present: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.external_stop_present);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "shore_power_connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shore_power_connected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "shore_power_ov: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shore_power_ov);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.battery_connected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "power_12v_user_nominal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.power_12v_user_nominal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "manual_charger_connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.manual_charger_connected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "measured_battery: ";
    Printer<float>::stream(s, indent + "  ", v.measured_battery);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "measured_12v: ";
    Printer<float>::stream(s, indent + "  ", v.measured_12v);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "measured_5v: ";
    Printer<float>::stream(s, indent + "  ", v.measured_5v);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "computer_current: ";
    Printer<float>::stream(s, indent + "  ", v.computer_current);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_current: ";
    Printer<float>::stream(s, indent + "  ", v.total_current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DINGO_MSGS_MESSAGE_STATUS_H
